/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicContactsPanel.java
 *
 * Created on Jan 28, 2012, 10:36:17 AM
 */
package com.bman917.jcontacts.ui.forms;

import com.bman917.jcontacts.models.ContactEntry;
import com.bman917.jcontacts.models.ContactEntryDataModel;
import com.jchan.jtableutils.ModelUtil;
import java.util.List;

/**
 *
 * @author Mr Jacky
 */
public class BasicContactsPanel extends javax.swing.JPanel {

    ContactEntryDataModel model;
    
    /** Creates new form BasicContactsPanel */
    public BasicContactsPanel() {
        
        model = new ContactEntryDataModel();
        
        initComponents();
    }
    
    public ContactEntryDataModel getModel() {
        return model;
    }
    
    public void loadDate(List<ContactEntry> list) {
        model.addRows(list);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(model);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        ModelUtil.handlKeyPressedTabEvent(evt, model, jTable1);
        ModelUtil.handleKeyPressedEscapeEvent(evt, model, jTable1);
}//GEN-LAST:event_jTable1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
